fix: Exclude appium from dev dependencies (#35)

diff --git a/.azure-pipelines.yml b/.azure-pipelines.yml
--- a/.azure-pipelines.yml
+++ b/.azure-pipelines.yml
@@ -15,7 +15,9 @@ stages:
   - job: Node_Unit_Tests
     steps:
     - template: azure-templates/node_setup_steps.yml
-    - script: npm install
+    - script: |
+        npm install -g appium@next
+        npm install
     - script: npm run test
 
 - stage: Integration_Tests
@@ -26,5 +28,26 @@ stages:
       _FORCE_LOGS: 1
     steps:
     - template: azure-templates/node_setup_steps.yml
-    - script: npm install
-    - script: npm run e2e-test
+    - script: |
+        npm install -g appium@next
+        npm install
+    - script: |
+        export APPIUM_TEST_SERVER_PORT=4567
+        export APPIUM_TEST_SERVER_HOST=127.0.0.1
+        export cwd=$(pwd)
+        pushd "$cwd"
+        cd ~
+        appium driver install --source=local "$cwd"
+        appium server --port=$APPIUM_TEST_SERVER_PORT --address=$APPIUM_TEST_SERVER_HOST &
+        popd
+        secondsStarted=$(date +%s)
+        while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+          sleep 0.1
+          secondsElapsed=$(( $(date +%s) - secondsStarted ))
+          if [[ $secondsElapsed -gt 30 ]]; then
+            echo "Appium server was unable to start within 30 seconds timeout"
+            exit 1
+          fi
+        done
+
+        npm run e2e-test
