extract server startup

diff --git a/.azure-pipelines.yml b/.azure-pipelines.yml
--- a/.azure-pipelines.yml
+++ b/.azure-pipelines.yml
@@ -31,5 +31,23 @@ stages:
     - script: |
         npm install -g appium@next
         npm install
-        appium driver install --source=local "$(pwd)"
-    - script: npm run e2e-test
+    - script: |
+        export APPIUM_TEST_SERVER_PORT=4567
+        export APPIUM_TEST_SERVER_HOST=127.0.0.1
+        export cwd=$(pwd)
+        pushd "$cwd"
+        cd ~
+        appium driver install --source=local "$cwd"
+        appium server --port=$APPIUM_TEST_SERVER_PORT --address=$APPIUM_TEST_SERVER_HOST &
+        popd
+        secondsStarted=$(date +%s)
+        while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+          sleep 0.1
+          secondsElapsed=$(( $(date +%s) - secondsStarted ))
+          if [[ $secondsElapsed -gt 5 ]]; then
+            echo "Appium server was unable to start within 5 seconds timeout"
+            exit 1
+          fi
+        done
+
+        npm run e2e-test
